### ISSUE TITLE
Criar Pikomons

### ISSUE THREAD

**Issue by CaioHOF** [CaioHOF/Projeto2#1]
------------------------------------------------TxT 1--------------------------------------------------------------
**ATRIBUTOS:** 
Nome
Id
Hp
atk
def
SpA
SpD
Spd
Golpe1
Golpe2

**GUARDAR EM .bin**
------------------------------------------------TxT 2--------------------------------------------------------------
**ATRIBUTOS:** 
Id("Chave Estrangeira" <-- TxT 1)
Arte
**GUARDAR EM .bin**

**Comment by PuDiM6241** [comment]
https://manytools.org/hacker-tools/convert-images-to-ascii-art/

**Comment by 1luketa1** [comment]
[Pikomon Files.txt](https://github.com/user-attachments/files/17263245/Pikomon.Files.txt)
nada pronto fora as artes. apenas o que já foi feito, stats temporários, sem tipos

**Comment by 1luketa1** [comment]
novos pikomons. nada pronto fora as artes. apenas o que já foi feito, stats temporários, sem tipos
[Pikomon Files.txt](https://github.com/user-attachments/files/17346995/Pikomon.Files.txt)

**Comment by 1luketa1** [comment]
[Pikomon.Files.txt](https://github.com/user-attachments/files/17423199/Pikomon.Files.txt)
[rascunho.batalha.txt](https://github.com/user-attachments/files/17423200/rascunho.batalha.txt)
