### ISSUE TITLE
Funções para a visualização de dados\debug

### ISSUE THREAD

**Issue by PuDiM6241** [CaioHOF/Projeto2#7]
arrumar as funções de debug, elas estão tentando imprimir as structs antigas, muitos dados trocaram o nome ou pararam de existir

**Comment by CaioHOF** [comment]
debugPlayers Feito

**Comment by CaioHOF** [comment]
DebugPikomons Feito

**Comment by CaioHOF** [comment]
Itens Feito

**Comment by CaioHOF** [comment]
Skills feito
